name: checkmarx-flyway-scan

on:
  workflow_dispatch:
    inputs:
      terraform_action:
        description: 'Terraform Action'     
        required: true
        default: 'build-flyway-image'
        type: choice
        options:
          - plan
          - apply
          - destroy
          - build-flyway-image
      environment:
        description: 'Environment'
        required: true
        default: 'sandbox'
        type: choice
        options:
        - sandbox

permissions:
  contents: read
  security-events: write
  id-token: write

jobs:
  checkmarx-image-scan:
    runs-on: ubuntu-latest
    if: inputs.terraform_action == 'build-flyway-image'
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      id: docker-build
      run: |
        docker build -t complex-app:latest .

    - name: Run Checkmarx AST Scan
      uses: Checkmarx/ast-github-action@2.0.40
      with:
        base_uri: ${{ secrets.CX_BASE_URI }}
        cx_tenant: ${{ secrets.CX_TENANT }}
        cx_client_id: ${{ secrets.CX_CLIENT_ID }}
        cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
        project_name: ${{ github.repository }}
        branch: ${{ github.head_ref || github.ref }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        additional_params: --scan-types container-security --container-images complex-app:latest -s .
        repo_name: ${{ github.event.repository.name }}
        namespace: ${{ github.repository_owner }}
        pr_number: ${{ github.event.number }}
